name: CI/CD Firebase Deployment

# Trigger on merges/pushes to `main`
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

      # 1. Check out your repository
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Install Node.js (v20.x to satisfy Firebase CLI v14+)
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      # 3. Install dependencies
      - name: Install dependencies
        run: npm ci

      # 4. Run your unit tests (fail here if tests break)
      - name: Run tests
        run: npm run test   # or replace with: npx vitest run

      # 5. Build the production bundle
      - name: Build app
        run: npm run build

      # 6. Deploy to Firebase Hosting (“live” channel)
      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_INTERNET_STORE_D7A86 }}
          channelId: live
          projectId: internet-store-d7a86
